# Generated by Django 3.0.5 on 2022-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_about_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.TextField(max_length=200),
        ),
    ]
